### ISSUE TITLE
Cannot read an empty file

### ISSUE THREAD

**Issue by inra0** [talkingwallace/ChatGPT-Paper-Reader#5]
PyPDF2.errors.EmptyFileError: Cannot read an empty file. 

Right after I upload the pdf, and click Start Analyze.
The feedback that I got at "Ask question about your PDF" is always: I'm sorry, I still don't have enough information to provide you with a specific answer. Can you please provide me with the title of the paper or any additional information so I can assist you better?

**Comment by Alpaca4610** [comment]
https://github.com/talkingwallace/ChatGPT-Paper-Reader/issues/3

**Comment by inra0** [comment]
ah, my bad...

**Comment by shenbohe** [comment]
python3.9/site-packages/PyPDF2/_reader.py", line 1455, in _basic_validation
    raise EmptyFileError("Cannot read an empty file")
PyPDF2.errors.EmptyFileError: Cannot read an empty file

**Comment by inra0** [comment]
pip install gradio==3.15.0
